---
# vi: ts=2 sw=2 et:
#
name: Unit tests
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        run_phase: [WATCHDOG_TRUE, WATCHDOG_FALSE]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - name: Build & test (${{ matrix.run_phase }})
        run: sudo -E .github/workflows/unit_tests.sh ${{ matrix.run_phase }}
